name: Sync

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          source-repo: "git@github.com:doocs/doocs.github.io.git"
          destination-repo: "git@gitee.com:Doocs/doocs.git"

    - name: Rebuild Gitee Pages
      uses: mizuka-wu/gitee-pages-action@v1.0.0
      with:
          repository: doocs/doocs
          cookie: ${{ secrets.GITEE_COOKIE }}
          branch: master
